### ISSUE TITLE
Cleaning up after cmake/ecflow/boost build

### ISSUE THREAD

**Issue by martynasLhms** [Hirlam/HarmonieContainers#9]
A suggestion for full Harmonie build images is to remove /tmp/build_all folder after the installation of the necessary packages in the image is complete. 

Otherwise it is incorporated into the container, and is not cleaned afterwards. Eats up quite some extra space, which sometimes is not welcome in smaller systems.

So unless we need the compiled sources staying there, for whatever reason, I can create a pull request to remove those from the containers.

**Comment by martynasLhms** [comment]
https://github.com/Hirlam/HarmonieContainers/pull/10

**Comment by ewhelan** [comment]
I think PR #10 resolves this issue. Thanks @martynasLhms.
